spring:
  datasource:
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    url: "jdbc:derby:${user.home}/.kanbanWebAppDB/test;create=true"
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
